language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install --upgrade pytest
  - pip install codecov pytest-cov pytest-pep8
  - pip install --upgrade numpy cython
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then pip install --upgrade sphinx; fi
  - pip install -e .

script:
  - py.test -v --cov pytng --pep8 pytng tests

after_success:
  - codecov
  # only need to build docs on 3.6 version
  # touch .nojekyll else github-pages messes up theme
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then cd docs && make html && touch ./_build/html/.nojekyll && cd ../; fi

deploy:
  # stuff related to deploying to gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  on:
    branch: master
    python: "3.6"
  local_dir: docs/_build/html
  project_name: pytng
